### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by andrep** [share/share-codemirror#2]
Hi there,

When I try to install `share-codemirror`, the postinstall script exits with a problem:

```
% npm install share-codemirror
npm http GET https://registry.npmjs.org/share-codemirror
npm http 304 https://registry.npmjs.org/share-codemirror

> share-codemirror@0.0.3 postinstall /Users/andre/Code/github/aed/node_modules/share-codemirror
> cd node_modules/share && npm install

sh: line 0: cd: node_modules/share: No such file or directory
npm ERR! weird error 1
npm ERR! not ok code 0
```

This seems odd since the travis-ci builds are passing. Can you just confirm that this is a problem on my side?

Thanks!

**Comment by aslakhellesoy** [comment]
I just release 0.0.4 which should work ok. Thanks for the heads up!

**Comment by andrep** [comment]
Oh wow, that was fast. Thank you Aslak!

**Comment by nornagon** [comment]
Oh, hi Andre :)

## 

j
